# Generated by Django 4.2.3 on 2023-07-06 19:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(help_text='Name of City', max_length=30, verbose_name='City Name')),
                ('city_state_name', models.CharField(help_text='Name of State', max_length=30, verbose_name='City State')),
                ('city_boundary_coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Boundary Coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='CrimeDataYear',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murder_assault', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Murder and Assault')),
                ('kidnapping_abduction', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Kidnapping and Abduction')),
                ('sexual_assault', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Sexual Assault')),
                ('riot', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Riots')),
                ('theft_burglary', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Theft and Burglary')),
                ('accident_prone_areas', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Accident Prone Areas')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CrimeMapper.citylist')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CrimeMapper.crimedatayear')),
            ],
        ),
    ]
