# Generated by Django 4.2.3 on 2023-07-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrimeMapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimedatayear',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
